### ISSUE TITLE
Exception while reading some ABF files

### ISSUE THREAD

**Issue by Taomach** [swharden/pyABF#101]
I use Bruxton Review to convert my data from HEKA Patchmaster format to ABF1. The resulting files have their creation date in "%y%m%d" format instead of "%Y%m%d", which causes this exception while reading some of them:

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/pyabf/abf.py", line 86, in __init__
        self._readHeadersV1(fb)
      File "/usr/lib/python3.8/site-packages/pyabf/abf.py", line 158, in _readHeadersV1
        self._headerV1 = HeaderV1(fb)
      File "/usr/lib/python3.8/site-packages/pyabf/abfHeader.py", line 327, in __init__
        startDate = datetime.datetime.strptime(startDate, "%Y%m%d")
      File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
        tt, fraction, gmtoff_fraction = _strptime(data_string, format)
      File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
        raise ValueError("time data %r does not match format %r" %
    ValueError: time data '560108' does not match format '%Y%m%d'

This can be solved by wrapping the line 327 in abfHeader.py in the `try` statement:

            try:
                startDate = datetime.datetime.strptime(startDate, "%Y%m%d")
            except ValueError:
                startDate = datetime.datetime.strptime(startDate, "%y%m%d")

**Comment by t-b** [comment]
@Taomach Can you provide your patch as PR?

**Comment by swharden** [comment]
> @Taomach Can you provide your patch as PR?

Actually I got this one. I'll make an ABF1 and ABF2 file with intentionally corrupted date and time strings, then ensure both can be loaded without crashing

**Comment by swharden** [comment]
@Taomach thanks for bringing this issue to my attention!

I implemented exception handling like you suggested for both ABF1 and ABF2 files https://github.com/swharden/pyABF/commit/cc6a909025bf3280284c3622ad1a81f52a6e4330

This change is now live on the GitHub repo but not yet on pypi.

**Comment by swharden** [comment]
@Taomach actually, my fix just prevents the hard crash for invalid date codes. Invalid dates are reverted to epoch time 0. In your example you show this line:

```
ValueError: time data '560108' does not match format '%Y%m%d'
```

... which implies the datecode created by your ABF1-creating software is `560108`. Since I doubt the recording is from 1956 or 2056, I don't think changing `%Y` to `%y` is the best solution.

However, if you want to change this behavior in the future feel free to change both these regions and issue a pull request:

ABF1:

https://github.com/swharden/pyABF/blob/cc6a909025bf3280284c3622ad1a81f52a6e4330/src/pyabf/abfHeader.py#L325-L331

ABF2:

https://github.com/swharden/pyABF/blob/cc6a909025bf3280284c3622ad1a81f52a6e4330/src/pyabf/abfHeader.py#L412-L418

I'll leave this ticket open until the fix is live on pypi. Thanks again for bringing this up @Taomach!
