### ISSUE TITLE
installation into clean environment fails

### ISSUE THREAD

**Issue by NileGraddis** [swharden/pyABF#103]
using python 3.6. The issue is pyABF imports itself in order to get its version, and the `__init__.py` then imports modules which import external dependencies like numpy. If you've not already got numpy in your environment, this fails:
```
Collecting pyabf<2.3.0 (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/e2/1d/c404e7fdf9505959a5dab664457275b00c5cbfe777e85356b0aadede2430/pyabf-2.2.2.tar.gz (42kB)

    23% |███████▋                        | 10kB 27.0MB/s eta 0:00:01
    47% |███████████████▎                | 20kB 36.4MB/s eta 0:00:01
    71% |███████████████████████         | 30kB 45.7MB/s eta 0:00:01
    95% |██████████████████████████████▋ | 40kB 51.6MB/s eta 0:00:01
    100% |████████████████████████████████| 51kB 19.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-o2ws4z__/pyabf/setup.py", line 3, in <module>
        import pyabf
      File "/tmp/pip-install-o2ws4z__/pyabf/pyabf/__init__.py", line 18, in <module>
        from pyabf.abf import ABF
      File "/tmp/pip-install-o2ws4z__/pyabf/pyabf/abf.py", line 10, in <module>
        import pyabf.abfWriter
      File "/tmp/pip-install-o2ws4z__/pyabf/pyabf/abfWriter.py", line 14, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
```

A solution to this problem ought to also:
1. maintain a single source of truth for the version
2. not break users who are importing the flattened module

Some options:
1. Put the version in a text file and update the MANIFEST.in to include it. setup.py then reads that file, as does `__init__.py`.
2. make a bunch of external dependencies install_requires

The first option seems a bit cleaner.

**Comment by swharden** [comment]
Hey @NileGraddis, thanks for reporting this!

Python.org suggests 7 different ways to solve this problem. Your proposed solution is number 4: https://packaging.python.org/guides/single-sourcing-package-version/

I'll publish this on PyPi, test it in a new virtual environment (without numpy), and close this issue when I confirm it works.

**Comment by swharden** [comment]
It looks like it works now. `pip install pyabf` yields:

```
Collecting pyabf
  Downloading pyabf-2.2.3.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 464 kB/s
Collecting matplotlib>=2.1.0
  Downloading matplotlib-3.1.3-cp36-cp36m-win_amd64.whl (9.1 MB)
     |████████████████████████████████| 9.1 MB 6.4 MB/s
Collecting numpy>=1.13.3
  Downloading numpy-1.18.1-cp36-cp36m-win_amd64.whl (12.8 MB)
     |████████████████████████████████| 12.8 MB 204 kB/s
Collecting pytest>=3.0.7
  Downloading pytest-5.3.5-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 6.8 MB/s
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.1.0-cp36-none-win_amd64.whl (57 kB)
     |████████████████████████████████| 57 kB 2.5 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 2.8 MB/s
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 3.3 MB/s
Collecting packaging
  Downloading packaging-20.1-py2.py3-none-any.whl (36 kB)
Collecting wcwidth
  Downloading wcwidth-0.1.8-py2.py3-none-any.whl (17 kB)
Collecting atomicwrites>=1.0; sys_platform == "win32"
  Using cached atomicwrites-1.3.0-py2.py3-none-any.whl (5.9 kB)
Collecting py>=1.5.0
  Downloading py-1.8.1-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 953 kB/s
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.2.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 1.7 MB/s
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-1.5.0-py2.py3-none-any.whl (30 kB)
Collecting colorama; sys_platform == "win32"
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting attrs>=17.4.0
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: setuptools in c:\users\scott\anaconda3\envs\nonthin\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=2.1.0->pyabf) (45.2.0.post20200210)
Collecting six
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Downloading zipp-2.2.0-py36-none-any.whl (4.6 kB)
Building wheels for collected packages: pyabf
  Building wheel for pyabf (setup.py) ... done
  Created wheel for pyabf: filename=pyabf-2.2.3-py3-none-any.whl size=48009 sha256=077b2e67c14354d777b9c931921d29d63d104a4d4988ca74c82dd69e974db9d9
  Stored in directory: c:\users\scott\appdata\local\pip\cache\wheels\23\fc\1b\0b1d42a3880363d7f8243c15b92db2549a33826a757cdbc46c
Successfully built pyabf
Installing collected packages: numpy, kiwisolver, pyparsing, six, cycler, python-dateutil, matplotlib, packaging, wcwidth, atomicwrites, py, more-itertools, zipp, importlib-metadata, pluggy, colorama, attrs, pytest, pyabf
Successfully installed atomicwrites-1.3.0 attrs-19.3.0 colorama-0.4.3 cycler-0.10.0 importlib-metadata-1.5.0 kiwisolver-1.1.0 matplotlib-3.1.3 more-itertools-8.2.0 numpy-1.18.1 packaging-20.1 pluggy-0.13.1 py-1.8.1 pyabf-2.2.3 pyparsing-2.4.6 pytest-5.3.5 python-dateutil-2.8.1 six-1.14.0 wcwidth-0.1.8 zipp-2.2.0
```

Thanks again @NileGraddis!
