### ISSUE TITLE
Improve Python version enforcement

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#48]
## Add better support for Python version enforcement

- [x] Import [_version.py](https://github.com/swharden/pyABF/blob/master/src/pyabf/_version.py) in [setup.py](https://github.com/swharden/pyABF/blob/master/src/setup.py) to enforce version checking while using pip.
- [x] [_version.py](https://github.com/swharden/pyABF/blob/master/src/pyabf/_version.py) to fail better if < Python 3.6
- [x] Modify [setup.py](https://github.com/swharden/pyABF/blob/master/src/setup.py) to require python version ([like this?](https://stackoverflow.com/questions/45778790/specifying-the-minimum-python-version-required-for-a-module-in-pip))

## What Python version should be required?
pyABF uses lots of [f-strings](https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python) which according to [PEP 4098](https://www.python.org/dev/peps/pep-0498/) means Python <3.6 isn't supported. **Python 3.6** is probably the minimum supported by pyABF.

## Original Issue
Check how this fails if run on Python 2. I got an email from someone saying this happens (which is unclear).

```python
  File "/Users/dir/Library/Python/2.7/lib/python/site-packages/pyabf/__init__.py", line 9, in <module>
    from ._version import __version__
  File "/Users/dir/Library/Python/2.7/lib/python/site-packages/pyabf/_version.py", line 28
    errMsg = f"pyABF version {__version__} < required {versionNeeded}"
```

**Comment by swharden** [comment]
pyABF uses lots of [f-strings](https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python) which according to [PEP 4098](https://www.python.org/dev/peps/pep-0498/) means Python <3.6 isn't supported. 

Make Python 3.6 the minimum allowed version for pyABF.

**Comment by swharden** [comment]
According to an email I got, on Python 2.7 pyABF fails with the following message. This error is really unhelpful, and a simpler "pyABF requires Python 3.6 or newer" is needed.

```
Python 2.7.15 |Anaconda, Inc.| (default, May 1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyabf
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/rth/.local/lib/python2.7/site-packages/pyabf/__init__.py", line 9, in <module>
from ._version import __version__
File "/home/rth/.local/lib/python2.7/site-packages/pyabf/_version.py", line 28
errMsg = f"pyABF version {__version__} < required {versionNeeded}"
^
SyntaxError: invalid syntax
```

**Comment by swharden** [comment]
I added code to quietly exit if pyABF is imported on a Python distribution <3.6:
https://github.com/swharden/pyABF/blob/22fa96041959389c171f6ea590b2c098e2d74e8d/src/pyabf/__init__.py#L9-L12

and PyPi now knows Python >=3.6 is required:
https://github.com/swharden/pyABF/blob/b4ab3ae8553cd2bb16397c527dc88cc4a75035fb/src/setup.py#L32

**Comment by swharden** [comment]
Fixed in https://github.com/swharden/pyABF/releases/tag/2.0.27
