### ISSUE TITLE
improve ATF error handling

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#73]
Improve the error message displayed when you accidentally load an ABF into the ATF module. Currently the output is very confusing.

```python
pyabf.ATF("demo.abf")
```

```
Traceback (most recent call last):
  File "c:\Users\scott\Documents\GitHub\pyABF/src\pyabf\atf.py", line 39, in __init__
    signature, file_version = fh.readline().rstrip().split()
  File "C:\Users\scott\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 49: character maps to <undefined>
```

**Comment by swharden** [comment]
cf82e078536a9b4b65a3982e3dc275981b92aaee
